# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app_bundle.service.url_reader_service:
        class: AppBundle\Service\UrlReaderService

    app_bundle.service.preg_html_image_service:
            class: AppBundle\Service\PregHtmlImageService

    app_bundle.exception_listener:
            class: AppBundle\EventListener\ExceptionListener
            tags:
                - { name: kernel.event_listener, event: kernel.exception}


